# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adolphor
author: adolphor
email: 0haihzu0@gmail.com
description: > # this means to ignore newlines until "subpath:"
  学习笔记，技术分享，包括但不限于：
  Java，JVM，Spring，Spring MVC，myBatis，Tomcat，Maven，Git，Intellij
# baseurl: "/article" # 如果指定baseurl，提交到github会出现路径错误，所以在需要的时候手动添加路径比较好，比如 build.sh 中示例那样
destination: "./_site/www" # 指定编译路径可以方便管理nginx分流配置，且不影响github托管
twitter_username: 0haizhu0
github_username:  NorthFacing

# paginate
plugins:
    - jekyll-paginate
paginate: 10

# markdown语法解析引擎（GitHub强制要求）
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# 代码高亮引擎（GitHub强制要求）
highlighter: rouge

# disqus
disqusId: adolphor

# google 分析
googleAnalyticsId: UA-68980203-2

sass:
  sass_dir: ./css/_sass
  style: compressed

cacheVersion: 20200415

future: true
