---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service-for-hostname
  labels:
    app: nacos-service-for-hostname
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: server
      nodePort: 32536
      port: 8848
      protocol: TCP
      targetPort: 8848
    - name: client-rpc
      nodePort: 30582
      port: 9848
      protocol: TCP
      targetPort: 9848
    - name: raft-rpc
      nodePort: 32205
      port: 9849
      protocol: TCP
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - name: old-raft-rpc
      nodePort: 31455
      port: 7848
      protocol: TCP
      targetPort: 7848
  selector:
    app: nacosv210
  sessionAffinity: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-mysql-cm
data:
  mysql.host: "rm-bp1z907t13ljt4k70.mysql.rds.aliyuncs.com"
  mysql.db.name: "jy_microservice_auth"
  mysql.port: "3306"
  mysql.user: "jymsc_auth"
  mysql.password: "baB39DMJAy"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "nacosv210"
spec:
  selector:
    matchLabels:
      app: nacosv210
  replicas: 2
  template:
    metadata:
      name: "nacosv210"
      labels:
        app: nacosv210
    spec:
      containers:
        - name: k8snacos
          image: registry-vpc.cn-hangzhou.aliyuncs.com/jy-cloud-dev/nacos-server:v2.1.0
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_AUTH_ENABLE
              value: true
            - name: NACOS_REPLICAS
              value: "2"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-mysql-cm
                  key: mysql.password
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-service-for-hostname.gateway.svc.cluster.local:8848 nacos-1.nacos-service-for-hostname.gateway.svc.cluster.local:8848"
