apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  generation: 1
  labels:
    app: ali-nacos-1
  managedFields:
  name: ali-nacos-1
  namespace: nacos
  resourceVersion: '2517401'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ali-nacos-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ali-nacos-1
    spec:
      containers:
        - env:
            - name: MODE
              value: cluster
            - name: PREFER_HOST_MODE
              value: hostname
            - name: BASE_DIR
              value: /home/nacos
            - name: CLASSPATH
              value: '.:/home/nacos/conf:'
            - name: FUNCTION_MODE
              value: all
            - name: JAVA_HOME
              value: /usr/lib/jvm/java-1.8.0-openjdk
            - name: NACOS_USER
              value: nacos
            - name: JAVA
              value: /usr/lib/jvm/java-1.8.0-openjdk/bin/java
            - name: JVM_XMS
              value: 2g
            - name: JVM_XMX
              value: 2g
            - name: JVM_XMN
              value: 1g
            - name: JVM_MS
              value: 128m
            - name: JVM_MMS
              value: 320m
            - name: NACOS_DEBUG
              value: 'n'
            - name: TOMCAT_ACCESSLOG_ENABLED
              value: 'false'
            - name: TIME_ZONE
              value: Asia/Shanghai
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            - name: MYSQL_SERVICE_HOST
              value: rm-bp1z907t13ljt4k70.mysql.rds.aliyuncs.com
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: MYSQL_SERVICE_DB_NAME
              value: jy_microservice_auth
            - name: MYSQL_SERVICE_USER
              value: jymsc_auth
            - name: MYSQL_SERVICE_PASSWORD
              value: baB39DMJAy
            - name: MYSQL_DATABASE_NUM
              value: '1'
            - name: NACOS_AUTH_ENABLE
              value: 'true'
            - name: NACOS_SERVERS
              value: 'ali-nacos-1-svc:8848 ali-nacos-1-svc:8848 joy-nacos-1-svc:8848'
          image: 'registry-vpc.cn-hangzhou.aliyuncs.com/jy-cloud-dev/nacos:1.3.1'
          imagePullPolicy: IfNotPresent
          name: ali-nacos-1
          ports:
            - containerPort: 8848
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: '2022-05-16T05:42:03Z'
      lastUpdateTime: '2022-05-16T05:42:03Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2022-05-16T05:42:03Z'
      lastUpdateTime: '2022-05-16T05:42:03Z'
      message: ReplicaSet "ali-nacos-1-7645855b57" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
